---
title: "1-demo"
output: html_document
date: "2023-02-14"
---

Load necessary dependencies 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remotes::install_github("r-tmap/tmap")
pacman::p_load(here,dplyr,tidyverse,sf,terra,tmap,exactextractr)
```

Load shapefiles
```{r}
adm1 <- st_read(here::here("data-raw","shp","phl_adm_psa_namria_20231106_shp","phl_admbnda_adm1_psa_namria_20231106.shp"))
adm2 <- st_read(here::here("data-raw","shp","phl_adm_psa_namria_20231106_shp","phl_admbnda_adm2_psa_namria_20231106.shp"))
adm3 <- st_read(here::here("data-raw","shp","phl_adm_psa_namria_20231106_shp","phl_admbnda_adm3_psa_namria_20231106.shp"))
```

Plot ADM1 shapefile
```{r}
plot(st_geometry(adm1))
```

Plot ADM2 shapefile
```{r}
plot(st_geometry(adm2))
```
Plot ADM3 shapefile
```{r}
plot(st_geometry(adm3))
```
Zonal statistics
Example: Population by ADM1
```{r}
pop <- terra::rast(here::here("data-raw","raster","worldpop","phl_ppp_2020_constrained.tif")) %>%
  terra::aggregate(., fun="sum", fact=100, na.rm=TRUE)

map <- tm_shape(adm1) +
  tm_borders() +
  tm_shape(pop) + 
  tm_raster(col.scale = tm_scale_intervals(style = "quantile",
                                           values = rev(terrain.colors(64))), 
            col.legend = tm_legend(title="Population",
                                   reverse=TRUE,
            position = tm_pos_out("right"),
            legend.title.size = 1.2,
            legend.text.size = 1.0),
            col_alpha = 0.7)
map
map %>%
  tmap_save(here::here("figures","phi_pop.png"))

#calculate zonal statistics by summing population by polygon
adm1 <- adm1 %>%
  mutate(pop_tot = exactextractr::exact_extract(pop,.,"sum"))

map <-  tm_shape(adm1) +
  tm_borders() +
  tm_polygons(
        fill = "pop_tot",
        fill.scale = tm_scale_intervals(style = "quantile",
                                        values = rev(terrain.colors(64))),
        fill.legend = tm_legend(
          title = "Population total",
          reverse = TRUE,
          position = tm_pos_out("right"),
          legend.title.size = 1.2,
          legend.text.size = 1.0
        )) 
map
map %>%
  tmap_save(here::here("figures","phi_pop_by_polygon.png"))
```
Accessibility
Access to health facilities
```{r}
access_health <- terra::rast(here::here("data-raw","raster","friction_map","2020_motorized_friction_surface.geotiff.tif")) %>%
  crop(., adm1) %>%
  mask(., adm1)


map <- tm_shape(adm1) +
  tm_borders() +
  tm_shape(access_health) + 
  tm_raster(col.scale = tm_scale_intervals(style = "quantile",
                                           values = rev(terrain.colors(64))), 
            col.legend = tm_legend(title="Travel time to hospitals",
                                   reverse=TRUE,
            position = tm_pos_out("right"),
            legend.title.size = 1.2,
            legend.text.size = 1.0),
            col_alpha = 0.7)
map
map %>%
  tmap_save(here::here("figures","phi_health.png"))
```

Spatial join
```{r}
source(here::here("scripts","R","compute_accessibility.R")) #read in function
ncr <- adm1 %>%
  filter(ADM1_EN=="National Capital Region (NCR)")

friction.surface.filename<-here::here("data-raw","raster","friction_map","2020_motorized_friction_surface.geotiff.tif") 

school <- st_read(here::here("data-raw","shp","osm","philippines-latest-free.shp","gis_osm_pois_free_1.shp")) %>%
  filter(fclass %in% c("university","school")) 

map <- tm_shape(school) + 
  tm_dots()
map %>%
  tmap_save(here::here("figures","phi_school_dots_only.png"))

map <- tm_shape(adm1) +
  tm_borders() +
  tm_shape(school) + 
  tm_dots()
#map
map %>%
  tmap_save(here::here("figures","phi_school.png"))


map <- tm_shape(adm1) +
  tm_borders() +
  tm_shape(school) + 
  tm_dots() +
  tm_shape(ncr) +
  tm_borders(col="yellow",lwd=3)
#map
map %>%
  tmap_save(here::here("figures","phi_school_ncr.png"))

View(school)

school <- school %>%
  st_join(., adm1)
View(school)

school_ncr <- school %>%
  filter(ADM1_EN == "National Capital Region (NCR)")

#check how many schools are in NCR
dim(school_ncr)[1]

map <- tm_shape(ncr) +
  tm_borders() +
  tm_shape(school_ncr) + 
  tm_dots()
#map
map %>%
  tmap_save(here::here("figures","phi_school_in_ncr.png"))

```

Computing travel distance using the friction map
```{r}
school_pts <- school %>%
  dplyr::mutate(lon = sf::st_coordinates(.)[,1],
                lat = sf::st_coordinates(.)[,2]) %>%
  st_drop_geometry() %>%
  dplyr::select(lon, lat)

school %>% 
  write_csv(here::here("data-clean","schools.csv"))

point.filename <- here::here("data-clean","schools.csv")

T.filename<- here::here("data-clean","PHI_motorized_study_area_T.rds")
T.GC.filename<-here::here("data-clean","PHI_motorized_study_area_T_GC.rds")
output.filename<-here::here("data-clean","PHI_motorized_travel_time_osm_schools.tif")

compute_accesssibility(adm1,
                         transition.matrix.exists.flag,
                         friction.surface.filename,
                         point.filename,
                         T.filename,
                         T.GC.filename,
                         output.filename)
```
